[package]
name = "x"
version = "0.1.0"
authors = ["Alo√Øs Micard <alois@micard.lu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
